### ISSUE TITLE
修改《网站系统软件设计图和说明书》

### ISSUE THREAD

**Issue by nevertiree** [nevertiree/System_Integration_Homework#18]
本文档存在以下问题：

1. **逻辑性**过于强，但**可读性**过于弱。文档的大部分是合格的用例列表，但是还做不到可读性优良的“说明书”。
2. 纯用例列表的语法格式会给老师一种强烈的“骗页数”的感觉，我建议改称“一个词+一句话”的解释风格
 
把

> A2：某事情A
> 	前置条件：无
> 	1.某事情要这样子做
> 	后置条件：某事情B
> 

改称

>某事情A：某事情A要这样做，然后自动做B事情。

@Nightwingky 

举个例子，建议把以下文字

> A2：游客注册
> 	前置条件：无
> 	1.按平台要求填写注册信息
> 	后置条件：登录
> 

修改成

> 游客注册：游客按照平台要求填写注册信息，然后自动登录平台。

**Comment by nevertiree** [comment]
再举一个例子

> 	B3：用户参与个人社区内群聊
> 	前置条件：已经登录（A3）
> 	1、用户进入某个人社区，与个人社群内其他用户（包括社长、管理员）进行群聊
> 	后置条件：

修改成

> 群聊：用户进入某个人社区，与该群内其他用户（包括社长、管理员）进行群聊

**Comment by nevertiree** [comment]
欢迎Que同学在此评论回复 @Nightwingky

**Comment by Nightwingky** [comment]
😁
